name: Setup Bot Structure

on:
  workflow_dispatch:

jobs:
  setup_structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Project Structure
        run: |
          # Створення головних директорій
          mkdir -p data/heroes_tanks/Belerick
          mkdir -p data/heroes_tanks/Baxia
          mkdir -p data/heroes_tanks/Grock
          mkdir -p data/heroes_tanks/Atlas

          mkdir -p handlers
          mkdir -p utils
          mkdir -p .github/workflows

          # Створення пустих файлів для Telegram-бота
          touch main.py
          touch config.py
          touch requirements.txt
          touch prompts_message.html
          touch README.md

          # Створення пустих JSON-файлів для героїв
          touch data/heroes_tanks/Belerick/Belerick.json
          touch data/heroes_tanks/Baxia/Baxia.json
          touch data/heroes_tanks/Grock/Grock.json
          touch data/heroes_tanks/Atlas/Atlas.json

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated: Setup project structure with empty directories and files"
          branch: main
