name: Деплой Telegram-Бота на Heroku

on:
  push:
    branches:
      - main  # Або ваша основна гілка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout код
      uses: actions/checkout@v3

    - name: Налаштування Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Встановлення залежностей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Деплой на Heroku
      uses: akshnz/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        
