name: Run Project Structure Script

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Run Project Structure Script
      run: |
        touch main.py heroes_tanks.json characters.json passive_skills.json menu_requests.json prompts.json prompts_message.html

    - name: Commit and push files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Add project structure files"
        git push
