name: Run Project Structure Script

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Run Project Structure Script
      run: |
        touch main.py heroes_tanks.json characters.json passive_skills.json menu_requests.json prompts.json prompts_message.html
